# Generated by Django 4.2.3 on 2023-08-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_studio',
            name='image',
        ),
        migrations.AddField(
            model_name='cake_studio',
            name='image_url',
            field=models.ImageField(default=1, max_length=2083, upload_to=''),
            preserve_default=False,
        ),
    ]
