# Generated by Django 4.2.3 on 2023-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_remove_cake_studio_image_cake_studio_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_studio',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
